apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  # annotations:
  #   kubernetes.io/ingress.global-static-ip-name: "test-static"
spec:
  rules:
  - host: example.net
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: 80
